[package]
name = "jaggedarray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typenum = "1.17.0"
generic-array = "1.0.0"
static_assertions = "1.1.0"